build:
  image: python:2.7
  environment:
    - DB_ENV_DB=picsgrabber

  commands:
    - cd tasks
    - pip install --upgrade pip setuptools wheel
    - pip install -r requirements.txt


publish:
  docker:
    environment:
          - DOCKER_LAUNCH_DEBUG=true
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: arturoochoa/locust-k8s
    storage_driver: overlay

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: '#general'
    username: Sky-Gal
    template: >
      build #{{ build.number }} Locust-k8s build just finished with a {{ build.status }} status
